### ISSUE TITLE
max-cut-qiskit-optimization-demo- Graph Output

### ISSUE THREAD

**Issue by arian-code** [qiskit-community/qiskit-application-modules-demo-sessions#3]
Hi,
While running the code, I get the solution :  [[0, 1, 4], [2, 3]]

However, when I draw it using maxcut.draw(result, pos=pos):

nodes 0,1,3 are red, while 2, 4 are blue.

I have attached my jupyuter file for reference please. Kindly guide
[my-max-cut-qiskit-optimization-demo.pdf](https://github.com/qiskit-community/qiskit-application-modules-demo-sessions/files/7360277/my-max-cut-qiskit-optimization-demo.pdf)
.

**Comment by transdigiware** [comment]
jupiter notebook kindly

**Comment by delodealexandre** [comment]
Hi, 

I have a very similar issue but:

nodes 0,2,4 are red, while 1, 3 are blue.

**Comment by delodealexandre** [comment]
I have made this change: 

[](https://github.com/a-matsuo/qiskit-optimization/commit/4e9279ea367b76fcac2f58e9bc7423ef30143c42)

It works for me now.

**Comment by HuangJunye** [comment]
@arian-code @delodealexandre Sorry for the late reply. Do you still face this issue?

**Comment by garrison** [comment]
I sounds from @delodealexandre's post that this is most likely solved by https://github.com/Qiskit/qiskit-optimization/pull/263.

**Comment by HuangJunye** [comment]
@garrison Thanks for the pointer. Closing this issue. @arian-code @delodealexandre Please let us know if you still face the same issue with the latest Qiskit Optimization.
