### ISSUE TITLE
Add test suite (treon via GitHub Actions)

### ISSUE THREAD

**Issue by garrison** [qiskit-community/qiskit-application-modules-demo-sessions#7]
I believe this repository would benefit from having a test suite that evaluates each notebook using [treon](https://github.com/ReviewNB/treon) to check for any errors.  Running this periodically would allow us to ensure that the code provided in these demos continues to work in future versions of Qiskit.

**Comment by HuangJunye** [comment]
@garrison Sorry for the late reply. I am not sure how to do that. Can you give me some pointers?

**Comment by garrison** [comment]
I started a WIP in #10.
